spring:
  datasource:
    username: root
    password: 15295769532
    url: jdbc:mysql://localhost:3306/hhu_dbexam?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.beryl.pojo
  mapper-locations: classpath:/mapper/*.xml
